[logger]
level = "info"

[client]
toolbarMode = "minimal"

[server]
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 10000
headless = true
fileWatcherType = "none"
enableStaticServing = true

[theme]
primaryColor="#4458A3"
backgroundColor="#F6F6F6"
secondaryBackgroundColor="#E7EDF9"
textColor="#333332"
font="sans serif"

[browser]
gatherUsageStats = false
